/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SuperAdminRouteImport } from "./routes/super-admin";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as DoctorRouteImport } from "./routes/doctor";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SuperAdminIndexRouteImport } from "./routes/super-admin/index";
import { Route as DoctorIndexRouteImport } from "./routes/doctor/index";
import { Route as AdminIndexRouteImport } from "./routes/admin/index";
import { Route as SuperAdminWorkLocationsRouteImport } from "./routes/super-admin/work-locations";
import { Route as SuperAdminSpecialtiesRouteImport } from "./routes/super-admin/specialties";
import { Route as SuperAdminSchedulesRouteImport } from "./routes/super-admin/schedules";
import { Route as SuperAdminPermissionsRouteImport } from "./routes/super-admin/permissions";
import { Route as SuperAdminDoctorAccountsRouteImport } from "./routes/super-admin/doctor-accounts";
import { Route as SuperAdminDashboardRouteImport } from "./routes/super-admin/dashboard";
import { Route as SuperAdminAppointmentsRouteImport } from "./routes/super-admin/appointments";
import { Route as SuperAdminAdminAccountsRouteImport } from "./routes/super-admin/admin-accounts";
import { Route as DoctorDashboardRouteImport } from "./routes/doctor/dashboard";
import { Route as AdminDoctorAccountsRouteImport } from "./routes/admin/doctor-accounts";
import { Route as AdminDashboardRouteImport } from "./routes/admin/dashboard";
import { Route as SuperAdminDoctorAccountsIndexRouteImport } from "./routes/super-admin/doctor-accounts.index";
import { Route as SuperAdminAdminAccountsIndexRouteImport } from "./routes/super-admin/admin-accounts.index";
import { Route as SuperAdminWorkLocationsIdRouteImport } from "./routes/super-admin/work-locations/$id";
import { Route as SuperAdminSpecialtiesIdRouteImport } from "./routes/super-admin/specialties/$id";
import { Route as SuperAdminPermissionsUsersRouteImport } from "./routes/super-admin/permissions/users";
import { Route as SuperAdminPermissionsGroupsRouteImport } from "./routes/super-admin/permissions/groups";
import { Route as SuperAdminDoctorAccountsCreateRouteImport } from "./routes/super-admin/doctor-accounts.create";
import { Route as SuperAdminAdminAccountsCreateRouteImport } from "./routes/super-admin/admin-accounts.create";
import { Route as AdminDoctorAccountsCreateRouteImport } from "./routes/admin/doctor-accounts.create";
import { Route as SuperAdminDoctorAccountsIdViewRouteImport } from "./routes/super-admin/doctor-accounts.$id.view";
import { Route as SuperAdminDoctorAccountsIdEditRouteImport } from "./routes/super-admin/doctor-accounts.$id.edit";
import { Route as SuperAdminAdminAccountsIdViewRouteImport } from "./routes/super-admin/admin-accounts.$id.view";
import { Route as SuperAdminAdminAccountsIdEditRouteImport } from "./routes/super-admin/admin-accounts.$id.edit";

const SuperAdminRoute = SuperAdminRouteImport.update({
	id: "/super-admin",
	path: "/super-admin",
	getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
	id: "/login",
	path: "/login",
	getParentRoute: () => rootRouteImport,
} as any);
const DoctorRoute = DoctorRouteImport.update({
	id: "/doctor",
	path: "/doctor",
	getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
	id: "/admin",
	path: "/admin",
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => SuperAdminRoute,
} as any);
const DoctorIndexRoute = DoctorIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => DoctorRoute,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => AdminRoute,
} as any);
const SuperAdminWorkLocationsRoute = SuperAdminWorkLocationsRouteImport.update({
	id: "/work-locations",
	path: "/work-locations",
	getParentRoute: () => SuperAdminRoute,
} as any);
const SuperAdminSpecialtiesRoute = SuperAdminSpecialtiesRouteImport.update({
	id: "/specialties",
	path: "/specialties",
	getParentRoute: () => SuperAdminRoute,
} as any);
const SuperAdminSchedulesRoute = SuperAdminSchedulesRouteImport.update({
	id: "/schedules",
	path: "/schedules",
	getParentRoute: () => SuperAdminRoute,
} as any);
const SuperAdminPermissionsRoute = SuperAdminPermissionsRouteImport.update({
	id: "/permissions",
	path: "/permissions",
	getParentRoute: () => SuperAdminRoute,
} as any);
const SuperAdminDoctorAccountsRoute =
	SuperAdminDoctorAccountsRouteImport.update({
		id: "/doctor-accounts",
		path: "/doctor-accounts",
		getParentRoute: () => SuperAdminRoute,
	} as any);
const SuperAdminDashboardRoute = SuperAdminDashboardRouteImport.update({
	id: "/dashboard",
	path: "/dashboard",
	getParentRoute: () => SuperAdminRoute,
} as any);
const SuperAdminAppointmentsRoute = SuperAdminAppointmentsRouteImport.update({
	id: "/appointments",
	path: "/appointments",
	getParentRoute: () => SuperAdminRoute,
} as any);
const SuperAdminAdminAccountsRoute = SuperAdminAdminAccountsRouteImport.update({
	id: "/admin-accounts",
	path: "/admin-accounts",
	getParentRoute: () => SuperAdminRoute,
} as any);
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
	id: "/dashboard",
	path: "/dashboard",
	getParentRoute: () => DoctorRoute,
} as any);
const AdminDoctorAccountsRoute = AdminDoctorAccountsRouteImport.update({
	id: "/doctor-accounts",
	path: "/doctor-accounts",
	getParentRoute: () => AdminRoute,
} as any);
const AdminDashboardRoute = AdminDashboardRouteImport.update({
	id: "/dashboard",
	path: "/dashboard",
	getParentRoute: () => AdminRoute,
} as any);
const SuperAdminDoctorAccountsIndexRoute =
	SuperAdminDoctorAccountsIndexRouteImport.update({
		id: "/",
		path: "/",
		getParentRoute: () => SuperAdminDoctorAccountsRoute,
	} as any);
const SuperAdminAdminAccountsIndexRoute =
	SuperAdminAdminAccountsIndexRouteImport.update({
		id: "/",
		path: "/",
		getParentRoute: () => SuperAdminAdminAccountsRoute,
	} as any);
const SuperAdminWorkLocationsIdRoute =
	SuperAdminWorkLocationsIdRouteImport.update({
		id: "/$id",
		path: "/$id",
		getParentRoute: () => SuperAdminWorkLocationsRoute,
	} as any);
const SuperAdminSpecialtiesIdRoute = SuperAdminSpecialtiesIdRouteImport.update({
	id: "/$id",
	path: "/$id",
	getParentRoute: () => SuperAdminSpecialtiesRoute,
} as any);
const SuperAdminPermissionsUsersRoute =
	SuperAdminPermissionsUsersRouteImport.update({
		id: "/users",
		path: "/users",
		getParentRoute: () => SuperAdminPermissionsRoute,
	} as any);
const SuperAdminPermissionsGroupsRoute =
	SuperAdminPermissionsGroupsRouteImport.update({
		id: "/groups",
		path: "/groups",
		getParentRoute: () => SuperAdminPermissionsRoute,
	} as any);
const SuperAdminDoctorAccountsCreateRoute =
	SuperAdminDoctorAccountsCreateRouteImport.update({
		id: "/create",
		path: "/create",
		getParentRoute: () => SuperAdminDoctorAccountsRoute,
	} as any);
const SuperAdminAdminAccountsCreateRoute =
	SuperAdminAdminAccountsCreateRouteImport.update({
		id: "/create",
		path: "/create",
		getParentRoute: () => SuperAdminAdminAccountsRoute,
	} as any);
const AdminDoctorAccountsCreateRoute =
	AdminDoctorAccountsCreateRouteImport.update({
		id: "/create",
		path: "/create",
		getParentRoute: () => AdminDoctorAccountsRoute,
	} as any);
const SuperAdminDoctorAccountsIdViewRoute =
	SuperAdminDoctorAccountsIdViewRouteImport.update({
		id: "/$id/view",
		path: "/$id/view",
		getParentRoute: () => SuperAdminDoctorAccountsRoute,
	} as any);
const SuperAdminDoctorAccountsIdEditRoute =
	SuperAdminDoctorAccountsIdEditRouteImport.update({
		id: "/$id/edit",
		path: "/$id/edit",
		getParentRoute: () => SuperAdminDoctorAccountsRoute,
	} as any);
const SuperAdminAdminAccountsIdViewRoute =
	SuperAdminAdminAccountsIdViewRouteImport.update({
		id: "/$id/view",
		path: "/$id/view",
		getParentRoute: () => SuperAdminAdminAccountsRoute,
	} as any);
const SuperAdminAdminAccountsIdEditRoute =
	SuperAdminAdminAccountsIdEditRouteImport.update({
		id: "/$id/edit",
		path: "/$id/edit",
		getParentRoute: () => SuperAdminAdminAccountsRoute,
	} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/admin": typeof AdminRouteWithChildren;
	"/doctor": typeof DoctorRouteWithChildren;
	"/login": typeof LoginRoute;
	"/super-admin": typeof SuperAdminRouteWithChildren;
	"/admin/dashboard": typeof AdminDashboardRoute;
	"/admin/doctor-accounts": typeof AdminDoctorAccountsRouteWithChildren;
	"/doctor/dashboard": typeof DoctorDashboardRoute;
	"/super-admin/admin-accounts": typeof SuperAdminAdminAccountsRouteWithChildren;
	"/super-admin/appointments": typeof SuperAdminAppointmentsRoute;
	"/super-admin/dashboard": typeof SuperAdminDashboardRoute;
	"/super-admin/doctor-accounts": typeof SuperAdminDoctorAccountsRouteWithChildren;
	"/super-admin/permissions": typeof SuperAdminPermissionsRouteWithChildren;
	"/super-admin/schedules": typeof SuperAdminSchedulesRoute;
	"/super-admin/specialties": typeof SuperAdminSpecialtiesRouteWithChildren;
	"/super-admin/work-locations": typeof SuperAdminWorkLocationsRouteWithChildren;
	"/admin/": typeof AdminIndexRoute;
	"/doctor/": typeof DoctorIndexRoute;
	"/super-admin/": typeof SuperAdminIndexRoute;
	"/admin/doctor-accounts/create": typeof AdminDoctorAccountsCreateRoute;
	"/super-admin/admin-accounts/create": typeof SuperAdminAdminAccountsCreateRoute;
	"/super-admin/doctor-accounts/create": typeof SuperAdminDoctorAccountsCreateRoute;
	"/super-admin/permissions/groups": typeof SuperAdminPermissionsGroupsRoute;
	"/super-admin/permissions/users": typeof SuperAdminPermissionsUsersRoute;
	"/super-admin/specialties/$id": typeof SuperAdminSpecialtiesIdRoute;
	"/super-admin/work-locations/$id": typeof SuperAdminWorkLocationsIdRoute;
	"/super-admin/admin-accounts/": typeof SuperAdminAdminAccountsIndexRoute;
	"/super-admin/doctor-accounts/": typeof SuperAdminDoctorAccountsIndexRoute;
	"/super-admin/admin-accounts/$id/edit": typeof SuperAdminAdminAccountsIdEditRoute;
	"/super-admin/admin-accounts/$id/view": typeof SuperAdminAdminAccountsIdViewRoute;
	"/super-admin/doctor-accounts/$id/edit": typeof SuperAdminDoctorAccountsIdEditRoute;
	"/super-admin/doctor-accounts/$id/view": typeof SuperAdminDoctorAccountsIdViewRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/login": typeof LoginRoute;
	"/admin/dashboard": typeof AdminDashboardRoute;
	"/admin/doctor-accounts": typeof AdminDoctorAccountsRouteWithChildren;
	"/doctor/dashboard": typeof DoctorDashboardRoute;
	"/super-admin/appointments": typeof SuperAdminAppointmentsRoute;
	"/super-admin/dashboard": typeof SuperAdminDashboardRoute;
	"/super-admin/permissions": typeof SuperAdminPermissionsRouteWithChildren;
	"/super-admin/schedules": typeof SuperAdminSchedulesRoute;
	"/super-admin/specialties": typeof SuperAdminSpecialtiesRouteWithChildren;
	"/super-admin/work-locations": typeof SuperAdminWorkLocationsRouteWithChildren;
	"/admin": typeof AdminIndexRoute;
	"/doctor": typeof DoctorIndexRoute;
	"/super-admin": typeof SuperAdminIndexRoute;
	"/admin/doctor-accounts/create": typeof AdminDoctorAccountsCreateRoute;
	"/super-admin/admin-accounts/create": typeof SuperAdminAdminAccountsCreateRoute;
	"/super-admin/doctor-accounts/create": typeof SuperAdminDoctorAccountsCreateRoute;
	"/super-admin/permissions/groups": typeof SuperAdminPermissionsGroupsRoute;
	"/super-admin/permissions/users": typeof SuperAdminPermissionsUsersRoute;
	"/super-admin/specialties/$id": typeof SuperAdminSpecialtiesIdRoute;
	"/super-admin/work-locations/$id": typeof SuperAdminWorkLocationsIdRoute;
	"/super-admin/admin-accounts": typeof SuperAdminAdminAccountsIndexRoute;
	"/super-admin/doctor-accounts": typeof SuperAdminDoctorAccountsIndexRoute;
	"/super-admin/admin-accounts/$id/edit": typeof SuperAdminAdminAccountsIdEditRoute;
	"/super-admin/admin-accounts/$id/view": typeof SuperAdminAdminAccountsIdViewRoute;
	"/super-admin/doctor-accounts/$id/edit": typeof SuperAdminDoctorAccountsIdEditRoute;
	"/super-admin/doctor-accounts/$id/view": typeof SuperAdminDoctorAccountsIdViewRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/admin": typeof AdminRouteWithChildren;
	"/doctor": typeof DoctorRouteWithChildren;
	"/login": typeof LoginRoute;
	"/super-admin": typeof SuperAdminRouteWithChildren;
	"/admin/dashboard": typeof AdminDashboardRoute;
	"/admin/doctor-accounts": typeof AdminDoctorAccountsRouteWithChildren;
	"/doctor/dashboard": typeof DoctorDashboardRoute;
	"/super-admin/admin-accounts": typeof SuperAdminAdminAccountsRouteWithChildren;
	"/super-admin/appointments": typeof SuperAdminAppointmentsRoute;
	"/super-admin/dashboard": typeof SuperAdminDashboardRoute;
	"/super-admin/doctor-accounts": typeof SuperAdminDoctorAccountsRouteWithChildren;
	"/super-admin/permissions": typeof SuperAdminPermissionsRouteWithChildren;
	"/super-admin/schedules": typeof SuperAdminSchedulesRoute;
	"/super-admin/specialties": typeof SuperAdminSpecialtiesRouteWithChildren;
	"/super-admin/work-locations": typeof SuperAdminWorkLocationsRouteWithChildren;
	"/admin/": typeof AdminIndexRoute;
	"/doctor/": typeof DoctorIndexRoute;
	"/super-admin/": typeof SuperAdminIndexRoute;
	"/admin/doctor-accounts/create": typeof AdminDoctorAccountsCreateRoute;
	"/super-admin/admin-accounts/create": typeof SuperAdminAdminAccountsCreateRoute;
	"/super-admin/doctor-accounts/create": typeof SuperAdminDoctorAccountsCreateRoute;
	"/super-admin/permissions/groups": typeof SuperAdminPermissionsGroupsRoute;
	"/super-admin/permissions/users": typeof SuperAdminPermissionsUsersRoute;
	"/super-admin/specialties/$id": typeof SuperAdminSpecialtiesIdRoute;
	"/super-admin/work-locations/$id": typeof SuperAdminWorkLocationsIdRoute;
	"/super-admin/admin-accounts/": typeof SuperAdminAdminAccountsIndexRoute;
	"/super-admin/doctor-accounts/": typeof SuperAdminDoctorAccountsIndexRoute;
	"/super-admin/admin-accounts/$id/edit": typeof SuperAdminAdminAccountsIdEditRoute;
	"/super-admin/admin-accounts/$id/view": typeof SuperAdminAdminAccountsIdViewRoute;
	"/super-admin/doctor-accounts/$id/edit": typeof SuperAdminDoctorAccountsIdEditRoute;
	"/super-admin/doctor-accounts/$id/view": typeof SuperAdminDoctorAccountsIdViewRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| "/"
		| "/admin"
		| "/doctor"
		| "/login"
		| "/super-admin"
		| "/admin/dashboard"
		| "/admin/doctor-accounts"
		| "/doctor/dashboard"
		| "/super-admin/admin-accounts"
		| "/super-admin/appointments"
		| "/super-admin/dashboard"
		| "/super-admin/doctor-accounts"
		| "/super-admin/permissions"
		| "/super-admin/schedules"
		| "/super-admin/specialties"
		| "/super-admin/work-locations"
		| "/admin/"
		| "/doctor/"
		| "/super-admin/"
		| "/admin/doctor-accounts/create"
		| "/super-admin/admin-accounts/create"
		| "/super-admin/doctor-accounts/create"
		| "/super-admin/permissions/groups"
		| "/super-admin/permissions/users"
		| "/super-admin/specialties/$id"
		| "/super-admin/work-locations/$id"
		| "/super-admin/admin-accounts/"
		| "/super-admin/doctor-accounts/"
		| "/super-admin/admin-accounts/$id/edit"
		| "/super-admin/admin-accounts/$id/view"
		| "/super-admin/doctor-accounts/$id/edit"
		| "/super-admin/doctor-accounts/$id/view";
	fileRoutesByTo: FileRoutesByTo;
	to:
		| "/"
		| "/login"
		| "/admin/dashboard"
		| "/admin/doctor-accounts"
		| "/doctor/dashboard"
		| "/super-admin/appointments"
		| "/super-admin/dashboard"
		| "/super-admin/permissions"
		| "/super-admin/schedules"
		| "/super-admin/specialties"
		| "/super-admin/work-locations"
		| "/admin"
		| "/doctor"
		| "/super-admin"
		| "/admin/doctor-accounts/create"
		| "/super-admin/admin-accounts/create"
		| "/super-admin/doctor-accounts/create"
		| "/super-admin/permissions/groups"
		| "/super-admin/permissions/users"
		| "/super-admin/specialties/$id"
		| "/super-admin/work-locations/$id"
		| "/super-admin/admin-accounts"
		| "/super-admin/doctor-accounts"
		| "/super-admin/admin-accounts/$id/edit"
		| "/super-admin/admin-accounts/$id/view"
		| "/super-admin/doctor-accounts/$id/edit"
		| "/super-admin/doctor-accounts/$id/view";
	id:
		| "__root__"
		| "/"
		| "/admin"
		| "/doctor"
		| "/login"
		| "/super-admin"
		| "/admin/dashboard"
		| "/admin/doctor-accounts"
		| "/doctor/dashboard"
		| "/super-admin/admin-accounts"
		| "/super-admin/appointments"
		| "/super-admin/dashboard"
		| "/super-admin/doctor-accounts"
		| "/super-admin/permissions"
		| "/super-admin/schedules"
		| "/super-admin/specialties"
		| "/super-admin/work-locations"
		| "/admin/"
		| "/doctor/"
		| "/super-admin/"
		| "/admin/doctor-accounts/create"
		| "/super-admin/admin-accounts/create"
		| "/super-admin/doctor-accounts/create"
		| "/super-admin/permissions/groups"
		| "/super-admin/permissions/users"
		| "/super-admin/specialties/$id"
		| "/super-admin/work-locations/$id"
		| "/super-admin/admin-accounts/"
		| "/super-admin/doctor-accounts/"
		| "/super-admin/admin-accounts/$id/edit"
		| "/super-admin/admin-accounts/$id/view"
		| "/super-admin/doctor-accounts/$id/edit"
		| "/super-admin/doctor-accounts/$id/view";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	AdminRoute: typeof AdminRouteWithChildren;
	DoctorRoute: typeof DoctorRouteWithChildren;
	LoginRoute: typeof LoginRoute;
	SuperAdminRoute: typeof SuperAdminRouteWithChildren;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/super-admin": {
			id: "/super-admin";
			path: "/super-admin";
			fullPath: "/super-admin";
			preLoaderRoute: typeof SuperAdminRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/login": {
			id: "/login";
			path: "/login";
			fullPath: "/login";
			preLoaderRoute: typeof LoginRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/doctor": {
			id: "/doctor";
			path: "/doctor";
			fullPath: "/doctor";
			preLoaderRoute: typeof DoctorRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/admin": {
			id: "/admin";
			path: "/admin";
			fullPath: "/admin";
			preLoaderRoute: typeof AdminRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/super-admin/": {
			id: "/super-admin/";
			path: "/";
			fullPath: "/super-admin/";
			preLoaderRoute: typeof SuperAdminIndexRouteImport;
			parentRoute: typeof SuperAdminRoute;
		};
		"/doctor/": {
			id: "/doctor/";
			path: "/";
			fullPath: "/doctor/";
			preLoaderRoute: typeof DoctorIndexRouteImport;
			parentRoute: typeof DoctorRoute;
		};
		"/admin/": {
			id: "/admin/";
			path: "/";
			fullPath: "/admin/";
			preLoaderRoute: typeof AdminIndexRouteImport;
			parentRoute: typeof AdminRoute;
		};
		"/super-admin/work-locations": {
			id: "/super-admin/work-locations";
			path: "/work-locations";
			fullPath: "/super-admin/work-locations";
			preLoaderRoute: typeof SuperAdminWorkLocationsRouteImport;
			parentRoute: typeof SuperAdminRoute;
		};
		"/super-admin/specialties": {
			id: "/super-admin/specialties";
			path: "/specialties";
			fullPath: "/super-admin/specialties";
			preLoaderRoute: typeof SuperAdminSpecialtiesRouteImport;
			parentRoute: typeof SuperAdminRoute;
		};
		"/super-admin/schedules": {
			id: "/super-admin/schedules";
			path: "/schedules";
			fullPath: "/super-admin/schedules";
			preLoaderRoute: typeof SuperAdminSchedulesRouteImport;
			parentRoute: typeof SuperAdminRoute;
		};
		"/super-admin/permissions": {
			id: "/super-admin/permissions";
			path: "/permissions";
			fullPath: "/super-admin/permissions";
			preLoaderRoute: typeof SuperAdminPermissionsRouteImport;
			parentRoute: typeof SuperAdminRoute;
		};
		"/super-admin/doctor-accounts": {
			id: "/super-admin/doctor-accounts";
			path: "/doctor-accounts";
			fullPath: "/super-admin/doctor-accounts";
			preLoaderRoute: typeof SuperAdminDoctorAccountsRouteImport;
			parentRoute: typeof SuperAdminRoute;
		};
		"/super-admin/dashboard": {
			id: "/super-admin/dashboard";
			path: "/dashboard";
			fullPath: "/super-admin/dashboard";
			preLoaderRoute: typeof SuperAdminDashboardRouteImport;
			parentRoute: typeof SuperAdminRoute;
		};
		"/super-admin/appointments": {
			id: "/super-admin/appointments";
			path: "/appointments";
			fullPath: "/super-admin/appointments";
			preLoaderRoute: typeof SuperAdminAppointmentsRouteImport;
			parentRoute: typeof SuperAdminRoute;
		};
		"/super-admin/admin-accounts": {
			id: "/super-admin/admin-accounts";
			path: "/admin-accounts";
			fullPath: "/super-admin/admin-accounts";
			preLoaderRoute: typeof SuperAdminAdminAccountsRouteImport;
			parentRoute: typeof SuperAdminRoute;
		};
		"/doctor/dashboard": {
			id: "/doctor/dashboard";
			path: "/dashboard";
			fullPath: "/doctor/dashboard";
			preLoaderRoute: typeof DoctorDashboardRouteImport;
			parentRoute: typeof DoctorRoute;
		};
		"/admin/doctor-accounts": {
			id: "/admin/doctor-accounts";
			path: "/doctor-accounts";
			fullPath: "/admin/doctor-accounts";
			preLoaderRoute: typeof AdminDoctorAccountsRouteImport;
			parentRoute: typeof AdminRoute;
		};
		"/admin/dashboard": {
			id: "/admin/dashboard";
			path: "/dashboard";
			fullPath: "/admin/dashboard";
			preLoaderRoute: typeof AdminDashboardRouteImport;
			parentRoute: typeof AdminRoute;
		};
		"/super-admin/doctor-accounts/": {
			id: "/super-admin/doctor-accounts/";
			path: "/";
			fullPath: "/super-admin/doctor-accounts/";
			preLoaderRoute: typeof SuperAdminDoctorAccountsIndexRouteImport;
			parentRoute: typeof SuperAdminDoctorAccountsRoute;
		};
		"/super-admin/admin-accounts/": {
			id: "/super-admin/admin-accounts/";
			path: "/";
			fullPath: "/super-admin/admin-accounts/";
			preLoaderRoute: typeof SuperAdminAdminAccountsIndexRouteImport;
			parentRoute: typeof SuperAdminAdminAccountsRoute;
		};
		"/super-admin/work-locations/$id": {
			id: "/super-admin/work-locations/$id";
			path: "/$id";
			fullPath: "/super-admin/work-locations/$id";
			preLoaderRoute: typeof SuperAdminWorkLocationsIdRouteImport;
			parentRoute: typeof SuperAdminWorkLocationsRoute;
		};
		"/super-admin/specialties/$id": {
			id: "/super-admin/specialties/$id";
			path: "/$id";
			fullPath: "/super-admin/specialties/$id";
			preLoaderRoute: typeof SuperAdminSpecialtiesIdRouteImport;
			parentRoute: typeof SuperAdminSpecialtiesRoute;
		};
		"/super-admin/permissions/users": {
			id: "/super-admin/permissions/users";
			path: "/users";
			fullPath: "/super-admin/permissions/users";
			preLoaderRoute: typeof SuperAdminPermissionsUsersRouteImport;
			parentRoute: typeof SuperAdminPermissionsRoute;
		};
		"/super-admin/permissions/groups": {
			id: "/super-admin/permissions/groups";
			path: "/groups";
			fullPath: "/super-admin/permissions/groups";
			preLoaderRoute: typeof SuperAdminPermissionsGroupsRouteImport;
			parentRoute: typeof SuperAdminPermissionsRoute;
		};
		"/super-admin/doctor-accounts/create": {
			id: "/super-admin/doctor-accounts/create";
			path: "/create";
			fullPath: "/super-admin/doctor-accounts/create";
			preLoaderRoute: typeof SuperAdminDoctorAccountsCreateRouteImport;
			parentRoute: typeof SuperAdminDoctorAccountsRoute;
		};
		"/super-admin/admin-accounts/create": {
			id: "/super-admin/admin-accounts/create";
			path: "/create";
			fullPath: "/super-admin/admin-accounts/create";
			preLoaderRoute: typeof SuperAdminAdminAccountsCreateRouteImport;
			parentRoute: typeof SuperAdminAdminAccountsRoute;
		};
		"/admin/doctor-accounts/create": {
			id: "/admin/doctor-accounts/create";
			path: "/create";
			fullPath: "/admin/doctor-accounts/create";
			preLoaderRoute: typeof AdminDoctorAccountsCreateRouteImport;
			parentRoute: typeof AdminDoctorAccountsRoute;
		};
		"/super-admin/doctor-accounts/$id/view": {
			id: "/super-admin/doctor-accounts/$id/view";
			path: "/$id/view";
			fullPath: "/super-admin/doctor-accounts/$id/view";
			preLoaderRoute: typeof SuperAdminDoctorAccountsIdViewRouteImport;
			parentRoute: typeof SuperAdminDoctorAccountsRoute;
		};
		"/super-admin/doctor-accounts/$id/edit": {
			id: "/super-admin/doctor-accounts/$id/edit";
			path: "/$id/edit";
			fullPath: "/super-admin/doctor-accounts/$id/edit";
			preLoaderRoute: typeof SuperAdminDoctorAccountsIdEditRouteImport;
			parentRoute: typeof SuperAdminDoctorAccountsRoute;
		};
		"/super-admin/admin-accounts/$id/view": {
			id: "/super-admin/admin-accounts/$id/view";
			path: "/$id/view";
			fullPath: "/super-admin/admin-accounts/$id/view";
			preLoaderRoute: typeof SuperAdminAdminAccountsIdViewRouteImport;
			parentRoute: typeof SuperAdminAdminAccountsRoute;
		};
		"/super-admin/admin-accounts/$id/edit": {
			id: "/super-admin/admin-accounts/$id/edit";
			path: "/$id/edit";
			fullPath: "/super-admin/admin-accounts/$id/edit";
			preLoaderRoute: typeof SuperAdminAdminAccountsIdEditRouteImport;
			parentRoute: typeof SuperAdminAdminAccountsRoute;
		};
	}
}

interface AdminDoctorAccountsRouteChildren {
	AdminDoctorAccountsCreateRoute: typeof AdminDoctorAccountsCreateRoute;
}

const AdminDoctorAccountsRouteChildren: AdminDoctorAccountsRouteChildren = {
	AdminDoctorAccountsCreateRoute: AdminDoctorAccountsCreateRoute,
};

const AdminDoctorAccountsRouteWithChildren =
	AdminDoctorAccountsRoute._addFileChildren(AdminDoctorAccountsRouteChildren);

interface AdminRouteChildren {
	AdminDashboardRoute: typeof AdminDashboardRoute;
	AdminDoctorAccountsRoute: typeof AdminDoctorAccountsRouteWithChildren;
	AdminIndexRoute: typeof AdminIndexRoute;
}

const AdminRouteChildren: AdminRouteChildren = {
	AdminDashboardRoute: AdminDashboardRoute,
	AdminDoctorAccountsRoute: AdminDoctorAccountsRouteWithChildren,
	AdminIndexRoute: AdminIndexRoute,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

interface DoctorRouteChildren {
	DoctorDashboardRoute: typeof DoctorDashboardRoute;
	DoctorIndexRoute: typeof DoctorIndexRoute;
}

const DoctorRouteChildren: DoctorRouteChildren = {
	DoctorDashboardRoute: DoctorDashboardRoute,
	DoctorIndexRoute: DoctorIndexRoute,
};

const DoctorRouteWithChildren =
	DoctorRoute._addFileChildren(DoctorRouteChildren);

interface SuperAdminAdminAccountsRouteChildren {
	SuperAdminAdminAccountsCreateRoute: typeof SuperAdminAdminAccountsCreateRoute;
	SuperAdminAdminAccountsIndexRoute: typeof SuperAdminAdminAccountsIndexRoute;
	SuperAdminAdminAccountsIdEditRoute: typeof SuperAdminAdminAccountsIdEditRoute;
	SuperAdminAdminAccountsIdViewRoute: typeof SuperAdminAdminAccountsIdViewRoute;
}

const SuperAdminAdminAccountsRouteChildren: SuperAdminAdminAccountsRouteChildren =
	{
		SuperAdminAdminAccountsCreateRoute: SuperAdminAdminAccountsCreateRoute,
		SuperAdminAdminAccountsIndexRoute: SuperAdminAdminAccountsIndexRoute,
		SuperAdminAdminAccountsIdEditRoute: SuperAdminAdminAccountsIdEditRoute,
		SuperAdminAdminAccountsIdViewRoute: SuperAdminAdminAccountsIdViewRoute,
	};

const SuperAdminAdminAccountsRouteWithChildren =
	SuperAdminAdminAccountsRoute._addFileChildren(
		SuperAdminAdminAccountsRouteChildren
	);

interface SuperAdminDoctorAccountsRouteChildren {
	SuperAdminDoctorAccountsCreateRoute: typeof SuperAdminDoctorAccountsCreateRoute;
	SuperAdminDoctorAccountsIndexRoute: typeof SuperAdminDoctorAccountsIndexRoute;
	SuperAdminDoctorAccountsIdEditRoute: typeof SuperAdminDoctorAccountsIdEditRoute;
	SuperAdminDoctorAccountsIdViewRoute: typeof SuperAdminDoctorAccountsIdViewRoute;
}

const SuperAdminDoctorAccountsRouteChildren: SuperAdminDoctorAccountsRouteChildren =
	{
		SuperAdminDoctorAccountsCreateRoute: SuperAdminDoctorAccountsCreateRoute,
		SuperAdminDoctorAccountsIndexRoute: SuperAdminDoctorAccountsIndexRoute,
		SuperAdminDoctorAccountsIdEditRoute: SuperAdminDoctorAccountsIdEditRoute,
		SuperAdminDoctorAccountsIdViewRoute: SuperAdminDoctorAccountsIdViewRoute,
	};

const SuperAdminDoctorAccountsRouteWithChildren =
	SuperAdminDoctorAccountsRoute._addFileChildren(
		SuperAdminDoctorAccountsRouteChildren
	);

interface SuperAdminPermissionsRouteChildren {
	SuperAdminPermissionsGroupsRoute: typeof SuperAdminPermissionsGroupsRoute;
	SuperAdminPermissionsUsersRoute: typeof SuperAdminPermissionsUsersRoute;
}

const SuperAdminPermissionsRouteChildren: SuperAdminPermissionsRouteChildren = {
	SuperAdminPermissionsGroupsRoute: SuperAdminPermissionsGroupsRoute,
	SuperAdminPermissionsUsersRoute: SuperAdminPermissionsUsersRoute,
};

const SuperAdminPermissionsRouteWithChildren =
	SuperAdminPermissionsRoute._addFileChildren(
		SuperAdminPermissionsRouteChildren
	);

interface SuperAdminSpecialtiesRouteChildren {
	SuperAdminSpecialtiesIdRoute: typeof SuperAdminSpecialtiesIdRoute;
}

const SuperAdminSpecialtiesRouteChildren: SuperAdminSpecialtiesRouteChildren = {
	SuperAdminSpecialtiesIdRoute: SuperAdminSpecialtiesIdRoute,
};

const SuperAdminSpecialtiesRouteWithChildren =
	SuperAdminSpecialtiesRoute._addFileChildren(
		SuperAdminSpecialtiesRouteChildren
	);

interface SuperAdminWorkLocationsRouteChildren {
	SuperAdminWorkLocationsIdRoute: typeof SuperAdminWorkLocationsIdRoute;
}

const SuperAdminWorkLocationsRouteChildren: SuperAdminWorkLocationsRouteChildren =
	{
		SuperAdminWorkLocationsIdRoute: SuperAdminWorkLocationsIdRoute,
	};

const SuperAdminWorkLocationsRouteWithChildren =
	SuperAdminWorkLocationsRoute._addFileChildren(
		SuperAdminWorkLocationsRouteChildren
	);

interface SuperAdminRouteChildren {
	SuperAdminAdminAccountsRoute: typeof SuperAdminAdminAccountsRouteWithChildren;
	SuperAdminAppointmentsRoute: typeof SuperAdminAppointmentsRoute;
	SuperAdminDashboardRoute: typeof SuperAdminDashboardRoute;
	SuperAdminDoctorAccountsRoute: typeof SuperAdminDoctorAccountsRouteWithChildren;
	SuperAdminPermissionsRoute: typeof SuperAdminPermissionsRouteWithChildren;
	SuperAdminSchedulesRoute: typeof SuperAdminSchedulesRoute;
	SuperAdminSpecialtiesRoute: typeof SuperAdminSpecialtiesRouteWithChildren;
	SuperAdminWorkLocationsRoute: typeof SuperAdminWorkLocationsRouteWithChildren;
	SuperAdminIndexRoute: typeof SuperAdminIndexRoute;
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
	SuperAdminAdminAccountsRoute: SuperAdminAdminAccountsRouteWithChildren,
	SuperAdminAppointmentsRoute: SuperAdminAppointmentsRoute,
	SuperAdminDashboardRoute: SuperAdminDashboardRoute,
	SuperAdminDoctorAccountsRoute: SuperAdminDoctorAccountsRouteWithChildren,
	SuperAdminPermissionsRoute: SuperAdminPermissionsRouteWithChildren,
	SuperAdminSchedulesRoute: SuperAdminSchedulesRoute,
	SuperAdminSpecialtiesRoute: SuperAdminSpecialtiesRouteWithChildren,
	SuperAdminWorkLocationsRoute: SuperAdminWorkLocationsRouteWithChildren,
	SuperAdminIndexRoute: SuperAdminIndexRoute,
};

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
	SuperAdminRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	AdminRoute: AdminRouteWithChildren,
	DoctorRoute: DoctorRouteWithChildren,
	LoginRoute: LoginRoute,
	SuperAdminRoute: SuperAdminRouteWithChildren,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();
